name = "nacho-reviews-api"
main = "app/main.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "d1-lmor152"
database_id = "${CF_DATABASE_ID}"

